jwt:
  secret: jwtsecretkey
spring:
#  datasource:
#    platform: mysql
#    url: jdbc:mysql://localhost:3306/biometric_auth
#    data-username: root
#    data-password: root

  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: '/h2'
      settings:
        trace: false
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082